### ISSUE TITLE
Entity path

### ISSUE THREAD

**Issue by a3020** [mainio/c5pkg_dbentities#2]
Is there a reason why you've hardcoded 'Src/Entity' into Package.php?

I don't quite see why entities necessarily need to be in that namespace. Wouldn't it be better to make this path configurable? E.g. protected $this->entityPath = 'src/Entity'.

**Comment by ahukkanen** [comment]
This package is actually outdated and it's already merged into the core. I just have forgotten to update the README.

In the core version, you can have these classes anywhere you want in your /src folder and there's no need to configure anything.

The path comes from our own preference of trying to follow the domain driven design priciples.

**Comment by ahukkanen** [comment]
And for clarification: You can have these classes anywhere (in /application, /packages and /concrete folders). By "core" I just meant that this functionality is now part of the c5 core.

**Comment by ahukkanen** [comment]
But the Entity class is not there since there might be differing preferences on that for different people. We like the ease of use to being able to assign and read the class variables easily but actually the Doctrine best practices do not suggest this. They suggest having only plain old PHP classes.

That's just our preference, so if you want to use that, I suggest including it manually in any project/package where you might need it (in case you want to use it).

**Comment by ahukkanen** [comment]
Please also see our reference implementation, it has been updated to use the core functionality:
https://github.com/mainio/c5_entities_example

**Comment by a3020** [comment]
Ah, I was looking for something to generate the doctrine classes. But you're right, it's in the core already! Thanks, it works perfectly!

**Comment by ahukkanen** [comment]
I just updated the README for the same information as here, so I'll close this issue.
